name: Pokemon Stock Checker

on:
  schedule:
    - cron: "*/2 * * * *"

  workflow_dispatch:


permissions:
  contents: write


jobs:
  check-stock:

    runs-on: ubuntu-latest


    steps:

      - name: 코드 가져오기
        uses: actions/checkout@v4


      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"


      - name: 라이브러리 설치
        run: |
          pip install requests playwright
          playwright install chromium


      - name: 재고 확인
        run: |
          python pokemon_checker.py


      - name: 상태 저장
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add status.json

          git commit -m "Update stock status" || echo "No changes"

          git push
