name: Pokemon Stock Checker

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:


jobs:
  check-stock:

    runs-on: ubuntu-latest

    steps:

      - name: 코드 가져오기
        uses: actions/checkout@v4


      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"


      - name: 필요한 라이브러리 설치
        run: |
          pip install requests


      - name: 재고 확인 실행
        run: |
          python pokemon_checker.py
